apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fastapi-api
  namespace: mis-prod
spec:
  template:
    spec:
      containers:
        - name: fastapi
          image: registry.onprem.local/mis/backend:latest
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: react-frontend
  namespace: mis-prod
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: registry.onprem.local/mis/frontend:latest
