apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: mis-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: mis/prod/application
        property: DATABASE_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: mis/prod/application
        property: REDIS_URL
    - secretKey: CELERY_BROKER_URL
      remoteRef:
        key: mis/prod/application
        property: CELERY_BROKER_URL
    - secretKey: JWT_PUBLIC_KEY
      remoteRef:
        key: mis/prod/application
        property: JWT_PUBLIC_KEY
