apiVersion: v1
kind: Service
metadata:
  name: celery-metrics
  namespace: mis-prod
  labels:
    app: celery-worker
spec:
  selector:
    app: celery-worker
  ports:
    - name: metrics
      port: 9091
      targetPort: 9091
