apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mis-portal
  namespace: mis-prod
spec:
  tls:
    - hosts:
        - portal.prod.gov.example
      secretName: mis-portal-tls
  rules:
    - host: portal.prod.gov.example
