apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: citizen-portal
      namespace: mis-prod
  - path: patch-backend-sa.yaml
    target:
      kind: ServiceAccount
      name: backend-sa
      namespace: mis-prod
  - path: patch-worker-sa.yaml
    target:
      kind: ServiceAccount
      name: worker-sa
      namespace: mis-prod
