apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/namespaces.yaml
  - rbac/serviceaccounts.yaml
  - rbac/roles.yaml
  - secrets/secretstore-aws.yaml
  - secrets/external-secrets.yaml
  - app/configmap.yaml
  - app/backend-analysis-template.yaml
  - services/backend-services.yaml
  - services/frontend-services.yaml
  - app/backend-rollout.yaml
  - app/frontend-rollout.yaml
  - workers/celery-deployment.yaml
  - autoscaling/hpa-backend.yaml
  - autoscaling/hpa-frontend.yaml
  - autoscaling/hpa-celery.yaml
  - autoscaling/pdb.yaml
  - networkpolicies/default-deny.yaml
  - networkpolicies/allow-ingress.yaml
  - networkpolicies/allow-egress-data.yaml
  - ingress/citizen-portal-ingress.yaml
  - observability/prometheus-rules.yaml
  - observability/servicemonitors.yaml
