apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-read-config
  namespace: mis-prod
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-read-config
  namespace: mis-prod
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: mis-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-read-config
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: worker-read-config
  namespace: mis-prod
subjects:
  - kind: ServiceAccount
    name: worker-sa
    namespace: mis-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-read-config
