apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: mis-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/mis-backend-irsa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: mis-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/mis-worker-irsa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: mis-prod
