apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: mis-prod
spec:
  provider:
    vault:
      server: https://vault.security.svc:8200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: mis-app
          serviceAccountRef:
            name: backend-sa
